# WHAT IS PYTORCH?
It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Getting Started

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
#from __future__ import print_function
import torch

#Construct a 5x3 matrix uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[          0.0000, -8589934592.0000,           0.0000],
        [-8589934592.0000,           0.0000,          -0.0000],
        [          0.0000,           0.0000,           0.0000],
        [          0.0000,           0.0000,           0.0000],
        [          0.0000,           0.0000,           0.0000]])


Lets create a matrix with random numbers

In [2]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0677, 0.6982, 0.1482],
        [0.2281, 0.2053, 0.8609],
        [0.9460, 0.2765, 0.2644],
        [0.3895, 0.4104, 0.3607],
        [0.2516, 0.8884, 0.7475]])


- Difference between uninitialized and initialized is that, in uninitialized the tensor is allocated in memory. Whatever in this memory is returned. In initialized, it allocates in new memory and fill it with randomly generated numbers between 0 and 1.

Construct a matrix filled zeros and of dtype long:

In [3]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- Long is an another version of 64 bit integer. You can use torch.long or torch.int64

In [4]:
# Constructing a tensor from Data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Creation a tensor from existed ones:

In [5]:
x = x.new_ones(5,3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1592,  1.9643,  1.1341],
        [-0.8683, -2.1385,  0.6737],
        [-0.0339, -0.4883,  1.4657],
        [-0.6522, -3.0376,  1.3596],
        [-1.3594, -1.0410, -0.3571]])


Get the size of it

In [6]:
x.size()

torch.Size([5, 3])

## Operations

## Addition

In [7]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.6778,  2.8166,  1.5405],
        [-0.2302, -1.9603,  1.5131],
        [-0.0333,  0.0219,  1.8354],
        [-0.4654, -2.4035,  1.8046],
        [-1.2272, -0.5675,  0.5196]])


In [8]:
# Syntax 2
print(torch.add(x,y))

tensor([[ 1.6778,  2.8166,  1.5405],
        [-0.2302, -1.9603,  1.5131],
        [-0.0333,  0.0219,  1.8354],
        [-0.4654, -2.4035,  1.8046],
        [-1.2272, -0.5675,  0.5196]])


In [9]:
# Providing an output place for addition
out = torch.empty(5, 3)
out = torch.add(x,y)
print(out)

tensor([[ 1.6778,  2.8166,  1.5405],
        [-0.2302, -1.9603,  1.5131],
        [-0.0333,  0.0219,  1.8354],
        [-0.4654, -2.4035,  1.8046],
        [-1.2272, -0.5675,  0.5196]])


In [10]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.6778,  2.8166,  1.5405],
        [-0.2302, -1.9603,  1.5131],
        [-0.0333,  0.0219,  1.8354],
        [-0.4654, -2.4035,  1.8046],
        [-1.2272, -0.5675,  0.5196]])


- Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [11]:
print(x)
print(x[:,1]) #For indexing you can use Numpy type features

tensor([[ 1.1592,  1.9643,  1.1341],
        [-0.8683, -2.1385,  0.6737],
        [-0.0339, -0.4883,  1.4657],
        [-0.6522, -3.0376,  1.3596],
        [-1.3594, -1.0410, -0.3571]])
tensor([ 1.9643, -2.1385, -0.4883, -3.0376, -1.0410])


If you want to resize/reshape tensor, you can use 'torch.view'

In [15]:
x = torch.randn(4,4)
print(x)
y = x.view(16)# Similar with numpy reshape function
z = x.view(-1,8)# -1 Means that give me appropriate number of row
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.3335, -1.7136, -1.4509, -1.0435],
        [-0.3898,  1.0967,  1.6114, -0.1005],
        [-0.1587, -1.6786, -2.0368,  0.1357],
        [-2.1033,  1.0643, -0.5947,  0.9620]])
tensor([[-0.3335, -1.7136, -1.4509, -1.0435, -0.3898,  1.0967,  1.6114, -0.1005],
        [-0.1587, -1.6786, -2.0368,  0.1357, -2.1033,  1.0643, -0.5947,  0.9620]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have one element in tensor, '.item()' can be used to get as a Python value.

In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.0841])
2.0841064453125


## NUMPY CONVERSION

Torch Tensor can be converted into Numpy array and vice versa. Torch Tensor and Numpy array shares the same memory locations.

Converting a Torch Tensor to a Numpy Array:

In [24]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


- Because of the same memory location, adding operation effect both of them.

In [25]:
## Converting Numpy Array to Torch Tensor

Effect of changing np array on Torch Tensor.

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1, out =a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA TENSORS

Tensors can be moved onto any device using .to method.

In [33]:
# Check first availability of Cuda in your computer
# 'torch.device' can be used in order to move tensors in and out of GPU.

if torch.cuda.is_available():
    device = torch.device("cuda") # a Cuda device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # Or just use '.to("cuda")
    z = x + y
    print(z)
    print(x.to("cpu", torch.double))