# WHAT IS PYTORCH?
It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- A deep learning research platform that provides maximum flexibility and speed

## Getting Started

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [27]:
#from __future__ import print_function
import torch

#Construct a 5x3 matrix uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -8.5899e+09, -2.7272e-35],
        [ 3.6902e+19,  5.6052e-45, -8.5899e+09],
        [-2.7272e-35,  1.0845e-19,  4.2039e-45],
        [-8.5899e+09, -2.7272e-35, -1.5849e+29],
        [ 2.8026e-45,  0.0000e+00,  0.0000e+00]])


In [28]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2816, 0.2489, 0.1133],
        [0.2508, 0.1935, 0.9030],
        [0.9062, 0.6839, 0.8540],
        [0.4342, 0.4738, 0.0267],
        [0.4047, 0.6002, 0.4497]])


- Difference between uninitialized and initialized is that, in uninitialized the tensor is allocated in memory. Whatever in this memory is returned. In initialized, it allocates in new memory and fill it with randomly generated numbers between 0 and 1.

Construct a matrix filled zeros and of dtype long:

In [14]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- Long is an another version of 64 bit integer. You can use torch.long or torch.int64

In [36]:
# Constructing a tensor from Data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Creation a tensor from existed ones:

In [37]:
x = x.new_ones(5,3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9204, -0.0239, -0.4775],
        [ 0.0745,  0.9714, -1.7687],
        [-1.8006,  0.0960,  0.6500],
        [-1.2762, -1.3536,  1.2531],
        [ 0.4923, -0.3494, -0.8489]])


Get the size of it

In [48]:
x.size()

torch.Size([5, 3])

## Operations

## Addition

In [51]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.9854,  0.9395, -0.1842],
        [ 0.7620,  1.8613, -1.2170],
        [-1.4789,  0.3406,  1.3560],
        [-0.3267, -0.8702,  1.9547],
        [ 0.9185,  0.5233, -0.8399]])


In [54]:
# Syntax 2
print(torch.add(x,y))

tensor([[ 0.9854,  0.9395, -0.1842],
        [ 0.7620,  1.8613, -1.2170],
        [-1.4789,  0.3406,  1.3560],
        [-0.3267, -0.8702,  1.9547],
        [ 0.9185,  0.5233, -0.8399]])


In [55]:
# Providing an output place for addition
out = torch.empty(5, 3)
out = torch.add(x,y)
print(out)

tensor([[ 0.9854,  0.9395, -0.1842],
        [ 0.7620,  1.8613, -1.2170],
        [-1.4789,  0.3406,  1.3560],
        [-0.3267, -0.8702,  1.9547],
        [ 0.9185,  0.5233, -0.8399]])


In [58]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.9059,  0.9156, -0.6617],
        [ 0.8365,  2.8327, -2.9857],
        [-3.2795,  0.4367,  2.0061],
        [-1.6029, -2.2237,  3.2078],
        [ 1.4107,  0.1739, -1.6888]])


- Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [60]:
print(x)
print(x[:,1]) #For indexing you can use Numpy type features

tensor([[ 0.9204, -0.0239, -0.4775],
        [ 0.0745,  0.9714, -1.7687],
        [-1.8006,  0.0960,  0.6500],
        [-1.2762, -1.3536,  1.2531],
        [ 0.4923, -0.3494, -0.8489]])
tensor([-0.0239,  0.9714,  0.0960, -1.3536, -0.3494])
